# Generated by Django 2.2.12 on 2020-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户自身的id')),
                ('sid', models.IntegerField(verbose_name='被滑动人的id')),
                ('mark', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('superlike', 'superlike')], max_length=16, verbose_name='滑动类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='滑动时间')),
            ],
        ),
    ]
