# Generated by Django 2.2.12 on 2020-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200511_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=None, max_length=256, verbose_name='个人头像的url地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='male', max_length=8, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=128, verbose_name='常居地'),
            preserve_default=False,
        ),
    ]
