# Generated by Django 2.2.12 on 2020-05-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200513_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_location', models.CharField(max_length=128, verbose_name='目标城市')),
                ('dating_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8, verbose_name='匹配的性别')),
                ('min_distance', models.IntegerField(default=0, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=50, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=True, verbose_name='不让陌生人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
